[package]
name = "godotsr2"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
byteorder = "1.5.0"
godot = "0.2.3"
zerocopy = "0.8.20"
zerocopy-derive = "0.8.20"

