[package]
name = "godotsr2"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
sr2 = { package = "sr2_types", path = "../sr2_types/" }
godot = "0.2.3"
