[package]
name = "types_validator"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
clap = { version = "4.5.30", features = ["derive"] }
colored = "3.0.0"
rust_search = "2.1.0"
sr2 = { package = "sr2_types", path = "../sr2_types/" }
