[package]
name = "chunk_mangler"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
clap = { version = "4.5.30", features = ["derive"] }
rand = "0.9.0"
sr2 = { package = "sr2_types", path = "../sr2_types/" }
